AP-16 | [BE] Add Health check API
teachmind/Parcel-Service pull request #1
Opened 2021-07-25 17:46 UTC by rdhawladar

2021-07-25 17:55 UTC, zrshishir commented
internal/app/model/entities.go this file should contain different model. Do we need internal/app/model/jwt.go file here in this service? Except these two files, it looks good to me.

2021-07-25 18:15 UTC, shuza commented on internal/app/server/server.go
> +func (s *server) pingHandler(w http.ResponseWriter, r *http.Request) {
write test case for `pingHandler`

2021-07-25 18:16 UTC, shuza requested changes
add test for `pingHandler`

2021-07-26 13:25 UTC, shuza commented on internal/app/server/server_test.go
> +func TestShutdown(t *testing.T) {
why this test is empty?

2021-07-26 13:25 UTC, shuza reviewed
test function should test something otherwise remove empty test function

2021-07-26 14:55 UTC, Asad-noor commented on internal/app/model/entities.go
>  package model
If there is no code then should we keep the file?

2021-07-26 14:58 UTC, Asad-noor commented on internal/app/model/entities.go
>  package model
Also, there are some other files and folders which are empty, if are not needed yet, we should remove them.

2021-07-26 16:15 UTC, merged