Feature/ap 8
teachmind/Parcel-Service pull request #3
Opened 2021-08-14 12:32 UTC by rdhawladar

2021-08-17 06:36 UTC, shuza commented on internal/app/model/entities.go
> +
remove this blank line

2021-08-17 06:46 UTC, shuza requested changes
refactor codes according to comments and remove comments for single line of code. single line of code should be readable and understandable without comment

2021-08-17 06:46 UTC, shuza commented on internal/app/model/response.go
> +var ErrEmpty = fmt.Errorf("empty") // Empty error
remove comment

2021-08-17 06:46 UTC, shuza commented on internal/app/parcel/repository.go
> +	insertParcelQuery  = `INSERT INTO parcel (user_id, carrier_id, source_address, destination_address, source_time, type, price, carrier_fee, company_fee) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`
at the time of parcel creation carrier_id will be empty so remove carrier_id from query

2021-08-17 06:46 UTC, shuza commented on internal/app/parcel/repository.go
> +	if _, err := r.db.ExecContext(ctx, insertParcelQuery, parcel.UserID, 1, parcel.SourceAddress, parcel.DestinationAddress, parcel.SourceTime, parcel.ParcelType, 200.0, 180.0, 20.0); err != nil {
don't hardcode price in repository. send it from service layer

2021-08-17 06:46 UTC, shuza commented on internal/app/parcel/service.go
> +// NewService is to generate for new repo
remoce comment

2021-08-17 06:46 UTC, shuza commented on internal/app/parcel/service.go
> +// CreaetParcel is to hash password, validate credentials and inserting data into database
remove comment

2021-08-17 06:46 UTC, shuza commented on internal/app/parcel/service.go
> +	/* if p, err := util.HashPassword(user.Password); err == nil {
if don't needed remove those code instead of comment out

2021-08-17 06:46 UTC, shuza commented on internal/app/server/halder_test.go
> +const (
don't use const at here. its only used by one test case so put it inside that test case

2021-08-17 06:46 UTC, shuza commented on internal/app/server/handler.go
> +	// validating input credentials for Parcel create
remove comment. single line of code you be readable without comment

2021-08-18 06:26 UTC, shuza requested changes
move pricing constant in service layer. layer service layer will call external component to get pricing data

2021-08-18 06:26 UTC, shuza commented on internal/app/server/handler.go
> +		CARRIER_FEE = 180.00
this should be in service layer. later service will call pricing service (external service) to get those value

2021-08-18 06:32 UTC, zrshishir requested changes

2021-08-18 06:32 UTC, zrshishir commented on internal/app/server/handler.go
> +		log.Error().Err(err).Msgf("[signUp] failed to create parcel Error: %v", err)
at line no 39 `[signUp]` should be chaged to `[parcel]` route.

2021-08-18 06:46 UTC, zrshishir requested changes

2021-08-18 06:46 UTC, zrshishir commented on internal/app/model/entities.go
> +	SourceTime         string  `json:"source_time" db:"source_time"`
`source_time` should be timestamp not string.

2021-08-18 13:55 UTC, zrshishir approved these changes

2021-08-22 07:39 UTC, shuza approved these changes
lgtm

2021-08-22 07:43 UTC, merged